import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import ArrowUpRight from 'lucide-react/dist/esm/icons/arrow-up-right.js';
import ArrowDown from 'lucide-react/dist/esm/icons/arrow-down.js';
import Github from 'lucide-react/dist/esm/icons/github.js';
import Linkedin from 'lucide-react/dist/esm/icons/linkedin.js';
import Download from 'lucide-react/dist/esm/icons/download.js';
import Mail from 'lucide-react/dist/esm/icons/mail.js';
import MapPin from 'lucide-react/dist/esm/icons/map-pin.js';
import Menu from 'lucide-react/dist/esm/icons/menu.js';
import X from 'lucide-react/dist/esm/icons/x.js';
import ScanFace from 'lucide-react/dist/esm/icons/scan-face.js';
import Box from 'lucide-react/dist/esm/icons/box.js';
import Workflow from 'lucide-react/dist/esm/icons/workflow.js';
import Fingerprint from 'lucide-react/dist/esm/icons/fingerprint.js';
import Check from 'lucide-react/dist/esm/icons/check.js';
import Code2 from 'lucide-react/dist/esm/icons/code-xml.js';
import {projects} from './projects';
import Internships from './Internships.jsx';
import './styles.css';
const external={target:'_blank',rel:'noopener noreferrer'};
function Visual({type}){return <div className={`project-visual ${type}`} aria-hidden="true"><div className="visual-grid"/>{type==='biometric'?<><div className="scan-frame"><Fingerprint size={105} strokeWidth={.8}/><div className="scan-line"/></div><span className="visual-label"><i/> IDENTITY VERIFIED</span><span className="visual-corner">CONFIDENCE 0.98</span></>:type==='store'?<><div className="orbit"/><div className="product-cube"><Box size={94} strokeWidth={.7}/></div><span className="visual-label">+ PLACE IN YOUR SPACE</span><span className="visual-corner">AR EXPERIENCE / 03</span></>:type==='email'?<><div className="workflow"><span><Mail/></span><b>······</b><span className="flow-core"><Workflow size={32}/></span><b>······</b><span><Check/></span></div><span className="visual-label"><i/> WORKFLOW ACTIVE</span><span className="visual-corner">CLASSIFY → ENCRYPT → DELIVER</span></>:<><div className="scan-frame face"><ScanFace size={104} strokeWidth={.8}/></div><span className="visual-label"><i/> ATTENDANCE CONFIRMED</span><span className="visual-corner">REAL-TIME RECOGNITION</span></>}</div>}
function ProjectLink({url,children,icon:Icon}){return url?<a href={url} {...external}><Icon size={15}/>{children}<ArrowUpRight size={14}/></a>:<span className="unavailable" title={`${children} URL has not been provided`}><Icon size={15}/>{children}<small>Coming soon</small></span>}
function App(){const [filter,setFilter]=useState('All projects'); const [menu,setMenu]=useState(false);return <><header><a className="logo" href="#home" aria-label="Douae home">da<span>.</span></a><nav className={menu?'open':''} aria-label="Main navigation">{['Studies','Internships','Projects','Skills','Contact'].map(x=><a key={x} href={`#${x.toLowerCase()}`} onClick={()=>setMenu(false)}>{x}</a>)}</nav><a className="nav-contact" href="mailto:annasridouae3@gmail.com">Let’s talk <ArrowUpRight size={16}/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></header>
<main><section id="home" className="hero"><div className="hero-content"><div className="eyebrow"><span className="status-dot"/> DATA SCIENCE & ARTIFICIAL INTELLIGENCE</div><h1>Turning data into<br/><span className="serif">something</span> <span className="accent serif">meaningful.</span></h1><p className="hero-intro">Hi, I’m <strong>Douae Annasri</strong> <span className="wave">↗</span><br/>An AI engineering student with internship experience at<br className="desktop-break"/> <strong>Leyton, Giift, and CBI</strong> — from RAG and AI agents<br className="desktop-break"/> to cloud infrastructure and security.</p><div className="hero-actions flex items-center"><a className="primary-button" href="#internships">Explore my profile <ArrowUpRight size={19}/></a><a className="resume-button" href={`${import.meta.env.BASE_URL}resume.pdf`} download>Download resume <Download size={17}/></a></div><div className="hero-meta"><span><MapPin size={14}/> Casablanca, Morocco</span><span className="meta-divider"/><span>Curious by nature. Engineer by training.</span></div></div><div className="hero-art" aria-hidden="true"><div className="art-top">NEURAL FIELD <span>01 — 04</span></div><div className="sphere"><div className="sphere-lines"/>{Array.from({length:9},(_,i)=><i key={i} style={{transform:`translate(-50%, -50%) rotate(${i*20}deg)`}}/>)}<div className="sphere-equator"/></div><span className="art-tag tag-one"><span/> Learning. Building. Evolving.</span><span className="art-tag tag-two"><Code2 size={14}/> Ideas → intelligent systems</span><div className="art-bottom">HUMAN CURIOSITY × MACHINE INTELLIGENCE <span>✳</span></div></div><div className="hero-bottom"><span>AI ENGINEERING / FULL-STACK DEVELOPMENT / AUTOMATION</span><a href="#studies">SCROLL TO EXPLORE <ArrowDown size={14}/></a></div></section>
<section id="studies" className="section"><div className="section-heading"><div><div className="eyebrow muted">01 / STUDIES</div><h2>The foundation for <span className="serif">what comes next.</span></h2></div></div><div className="timeline">{[['2024 — Present','Engineering Degree · Data Science & AI','ENSIASD · Taroudant'],['June 2024','Bachelor’s Degree · Computer Engineering','Hassan II University · Casablanca']].map(([date,title,school])=><div className="timeline-item" key={title}><span className="timeline-date">{date}</span><div><h3>{title}</h3><span className="company">{school}</span></div></div>)}</div></section>
<Internships/><section id="projects" className="section projects-section"><div className="section-heading"><div><div className="eyebrow muted">03 / MORE PROJECTS</div><h2>Ideas, made <span className="serif">real.</span></h2></div><p>A few things I’ve built.<br/>Each one a new problem, a new possibility.</p></div><div className="filters" aria-label="Filter projects">{['All projects','Computer vision','AI & automation','Development'].map(x=><button key={x} onClick={()=>setFilter(x)} aria-pressed={filter===x} className={filter===x?'active':''}>{x}{x==='All projects'&&<span>04</span>}</button>)}</div><div className="project-grid grid grid-cols-1 md:grid-cols-2">{projects.filter(p=>filter==='All projects'||filter===p.category).map(p=><article className="project-card" key={p.id}><Visual type={p.visual}/><div className="project-body"><div className="project-category">{p.category}<span>/{p.id}</span></div><h3>{p.title}</h3><p>{p.description}</p><div className="tags flex flex-wrap">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="project-metric"><strong>{p.metric}</strong><span>{p.metricLabel}</span></div><div className="project-links"><ProjectLink url={p.github} icon={Github}>GitHub repo</ProjectLink><ProjectLink url={p.live} icon={ArrowUpRight}>Live demo</ProjectLink></div></div></article>)}</div></section>
<section id="about" className="section about-section"><div><div className="eyebrow muted">04 / ABOUT & SKILLS</div><h2>Always curious.<br/><span className="serif">Always building.</span></h2><p>I’m a Data Science & AI engineering student at ENSIASD, with a foundation in computer engineering and a fascination for how intelligent systems can solve everyday challenges.</p><p>From semantic search and multi-agent workflows to computer vision and full-stack applications, I enjoy taking an idea all the way from exploration to implementation.</p><div className="languages">Arabic <span>Native</span> French <span>Professional</span> English <span>Professional</span></div></div><div className="skills" id="skills"><h3>My engineering toolkit <span>↗</span></h3>{[['AI & Machine Learning','Python','TensorFlow','Scikit-learn','NLP','LLMs','RAG','LangGraph','OpenCV'],['Development','React','Spring Boot','Node.js','FastAPI','Java','Kotlin','SQL'],['Cloud & Automation','Azure','Docker','Kubernetes','Hadoop','n8n','Intune','Defender','Git']].map(([label,...items])=><div className="skill-group" key={label}><h4>{label}</h4><div className="tags flex flex-wrap">{items.map(t=><span key={t}>{t}</span>)}</div></div>)}</div></section>
<section id="contact" className="section contact-section"><div className="eyebrow">05 / WHAT’S NEXT?</div><h2>Great things start<br/>with a <span className="serif accent">conversation.</span></h2><p>Have a project in mind, an opportunity, or just a good idea?<br/>I’d love to hear from you.</p><a className="contact-email" href="mailto:annasridouae3@gmail.com">annasridouae3@gmail.com <ArrowUpRight/></a><div className="socials"><a href="https://linkedin.com/in/douae-annasri/" {...external}><Linkedin size={17}/> LinkedIn <ArrowUpRight size={14}/></a><a href={`${import.meta.env.BASE_URL}resume.pdf`} download><Download size={17}/> Resume</a></div></section></main><footer><a className="logo" href="#home">da<span>.</span></a><span>© {new Date().getFullYear()} Douae Annasri</span><span>Built with curiosity. And React.</span><a href="#home">Back to top ↑</a></footer></>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
